import apt from "./assets/apt-1.jpeg"
import apt2 from "./assets/apt2.png"
import lady from "./assets/lady.jpg"

const properties = [
  {
    id: 2,
    image: apt,
    price: 1300,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 24,
    image: apt2,
    price: 960,
    address: "310 W 76th Ave",
    sqFeet: 784,
  },
  {
    id: 3,
    image: apt,
    price: 1350,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 4,
    image: apt2,
    price: 1400,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 5,
    image: apt,
    price: 1400,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 6,
    image: apt,
    price: 1450,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 7,
    image: apt,
    price: 1450,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 8,
    image: apt,
    price: 1450,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 9,
    image: apt,
    price: 1500,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 10,
    image: apt,
    price: 1500,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 11,
    image: apt,
    price: 1500,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 12,
    image: apt,
    price: 1500,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 13,
    image: apt,
    price: 1500,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 14,
    image: apt,
    price: 1550,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 15,
    image: apt,
    price: 1550,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 16,
    image: apt,
    price: 1550,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 17,
    image: apt,
    price: 1550,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 18,
    image: apt,
    price: 1550,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 19,
    image: apt,
    price: 1550,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 20,
    image: apt,
    price: 1600,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 21,
    image: apt,
    price: 1600,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 22,
    image: apt,
    price: 1650,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 23,
    image: apt,
    price: 1750,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 1,
    image: apt,
    price: 846,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 25,
    image: apt,
    price: 2392,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 26,
    image: apt,
    price: 2392,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 27,
    image: apt,
    price: 2200,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
  {
    id: 28,
    image: apt,
    price: 2250,
    address: "345 Hamilton Str.",
    sqFeet: 1211,
  },
]

const propDetails = {
  1: {
    image: apt,
    price: 846,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  2: {
    image: apt,
    price: 1300,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  3: {
    image: apt,
    price: 1350,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  4: {
    image: apt,
    price: 1400,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  5: {
    image: apt,
    price: 1400,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  6: {
    image: apt,
    price: 1450,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  7: {
    image: apt,
    price: 1450,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  8: {
    image: apt,
    price: 1450,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  9: {
    image: apt,
    price: 1500,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  10: {
    image: apt,
    price: 1500,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  11: {
    image: apt,
    price: 1500,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  12: {
    image: apt,
    price: 1500,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  13: {
    image: apt,
    price: 1500,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  14: {
    image: apt,
    price: 1550,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  15: {
    image: apt,
    price: 1550,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  16: {
    image: apt,
    price: 1550,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  17: {
    image: apt,
    price: 1550,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  18: {
    image: apt,
    price: 1550,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  19: {
    image: apt,
    price: 1550,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  20: {
    image: apt,
    price: 1600,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  21: {
    image: apt,
    price: 1600,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  22: {
    image: apt,
    price: 1650,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  23: {
    image: apt,
    price: 1750,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  24: {
    image: apt2,
    price: 960,
    address: "310 W 76th Ave",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 784,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  25: {
    image: apt,
    price: 2392,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  26: {
    image: apt,
    price: 2392,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  27: {
    image: apt,
    price: 2200,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
  28: {
    image: apt,
    price: 2250,
    address: "345 Hamilton Str.",
    city: "Anchorage",
    state: "Alaska",
    sqFeet: 1211,
    beds: 3,
    bathrooms: 1,
    pets: true,
    description: "",
    contact: {
      image: lady,
      name: "Samantha Johns",
      phone: "",
      rating: 4.78,
    },
  },
}

export { properties, propDetails }